[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  port = 3000
  functionsPort = 3001
  publish = "."
  functions = "netlify/functions"
  autoLaunch = true

# Configuración para el dominio sinapsislegal.com
[context.production]
  environment = { NODE_VERSION = "18" }

# Redirecciones para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

# Headers de seguridad y CORS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Headers de seguridad generales
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.conekta.io https://js.stripe.com https://www.paypal.com https://www.mercadopago.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; img-src 'self' data: https:; connect-src 'self' https://api.conekta.io https://cdn.conekta.io https://api.stripe.com https://api.paypal.com https://api.mercadopago.com;"

# Headers para archivos estáticos
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configuración del dominio
[build.environment]
  NODE_VERSION = "18" 